version: '3.9'
services:

  db:
    image: postgres:13.0-alpine
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d ${POSTGRES_DB}", "-U ${PGUSER}"]
      interval: 5s
      timeout: 10s
      retries: 10
    ports:
      - "5432:5432"

  celery_beat:
    build: &parser
      context: .
    env_file:
      - .env
    depends_on:
      - celery_worker

    command: celery -A celery_worker beat

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  celery_worker:
    build: *parser
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: celery -A celery_worker worker -P threads --without-gossip
volumes:
  postgres_data:
